language: clojure

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

addons:
  postgresql: "9.4"

services:
  - postgresql


before_script:
  - psql -c "CREATE DATABASE football; CREATE ROLE football WITH SUPERUSER LOGIN PASSWORD 'football'" -U postgres
